name: CakePHP fixtures benchmark

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 0 * * *"

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4', '8.0']
        db-type: [sqlite, mysql, pgsql]
        prefer-lowest: ['']
        include:
          - php-version: '7.2'
            db-type: 'mariadb'
          - php-version: '7.2'
            db-type: 'mysql'
            prefer-lowest: 'prefer-lowest'

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
      memcached:
        image: memcached
        ports:
          - 11211/tcp

    steps:
    - name: Setup MySQL latest
      if: matrix.db-type == 'mysql' && matrix.php-version != '7.2'
      run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cbench -p 3306:3306 -d mysql --default-authentication-plugin=mysql_native_password --disable-log-bin

    - name: Setup MySQL 5.6
      if: matrix.db-type == 'mysql' && matrix.php-version == '7.2'
      run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cbench -p 3306:3306 -d mysql:5.6 --character-set-server=utf8

    - name: Setup PostgreSQL latest
      if: matrix.db-type == 'pgsql' && matrix.php-version != '7.2'
      run: docker run --rm --name=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=cbench -p 5432:5432 -d postgres

    - name: Setup PostgreSQL 9.4
      if: matrix.db-type == 'pgsql' && matrix.php-version == '7.2'
      run: docker run --rm --name=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=cbench -p 5432:5432 -d postgres:9.4

    - uses: getong/mariadb-action@v1.1
      if: matrix.db-type == 'mariadb'
      with:
        mysql database: 'cbench'
        mysql root password: 'root'

    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, apcu, pdo_${{ matrix.db-type }}
        ini-values: apc.enable_cli = 1
        coverage: pcov

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Get date part for cache key
      id: key-date
      run: echo "::set-output name=date::$(date +'%Y-%m')"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

    run: |
        if [[ ${{ matrix.php-version }} == '8.0' ]]; then
          composer install --ignore-platform-reqs
        else
          composer install
        fi
        composer run-script post-install-cmd --no-interaction

    - name: Setup problem matchers for PHPUnit
      if: matrix.php-version == '7.4' && matrix.db-type == 'mysql'
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Run PHPUnit All Fixtures each time
      env:
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
      run: |
        if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then export DATABASE_TEST_URL='sqlite:///:memory:'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} != '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} == '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench?encoding=utf8'; fi
        if [[ ${{ matrix.db-type }} == 'mariadb' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then export DATABASE_TEST_URL='postgres://postgres:postgres@127.0.0.1/cbench'; fi
        vendor/bin/phpunit --filter AllFixturesTest

    - name: Run PHPUnit Half optimized fixtures
      env:
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
      run: |
        if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then export DATABASE_TEST_URL='sqlite:///:memory:'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} != '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} == '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench?encoding=utf8'; fi
        if [[ ${{ matrix.db-type }} == 'mariadb' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then export DATABASE_TEST_URL='postgres://postgres:postgres@127.0.0.1/cbench'; fi
        vendor/bin/phpunit --filter HalfOptimizedFixturesTest

    - name: Run PHPUnit Full optimized fixtures
      env:
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
      run: |
        if [[ ${{ matrix.db-type }} == 'sqlite' ]]; then export DATABASE_TEST_URL='sqlite:///:memory:'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} != '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} == '7.2' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench?encoding=utf8'; fi
        if [[ ${{ matrix.db-type }} == 'mariadb' ]]; then export DATABASE_TEST_URL='mysql://root:root@127.0.0.1/cbench'; fi
        if [[ ${{ matrix.db-type }} == 'pgsql' ]]; then export DATABASE_TEST_URL='postgres://postgres:postgres@127.0.0.1/cbench'; fi
        vendor/bin/phpunit --filter FullyOptimizedFixturesTest

  testsuite-windows:
    runs-on: windows-2019
    name: Windows - PHP 7.4 & SQL Server

    env:
      EXTENSIONS: mbstring, intl, apcu, pdo_sqlsrv
      PHP_VERSION: '7.4'

    steps:
    - uses: actions/checkout@v2

    - name: Get date part for cache key
      id: key-date
      run: echo "::set-output name=date::$(date +'%Y-%m')"

    - name: Setup PHP extensions cache
      id: php-ext-cache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        key: ${{ steps.key-date.outputs.date }}

    - name: Cache PHP extensions
      uses: actions/cache@v1
      with:
        path: ${{ steps.php-ext-cache.outputs.dir }}
        key: ${{ runner.os }}-php-ext-${{ steps.php-ext-cache.outputs.key }}
        restore-keys: ${{ runner.os }}-php-ext-${{ steps.php-ext-cache.outputs.key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        ini-values: apc.enable_cli = 1, extension = php_fileinfo.dll
        coverage: none

    - name: Setup SQLServer
      run: |
        # MSSQLLocalDB is the default SQL LocalDB instance
        SqlLocalDB start MSSQLLocalDB
        SqlLocalDB info MSSQLLocalDB
        sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "create database cbench;"

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

    run: |
        if [[ ${{ matrix.php-version }} == '8.0' ]]; then
          composer install --ignore-platform-reqs
        else
          composer install
        fi
        composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit All Fixtures all time
      env:
        DATABASE_TEST_URL: 'sqlserver://@(localdb)\MSSQLLocalDB/cbench'
      run: |
          vendor/bin/phpunit --filter AllFixturesTest

    - name: Run PHPUnit Half Optimized fixtures
      env:
        DATABASE_TEST_URL: 'sqlserver://@(localdb)\MSSQLLocalDB/cbench'
      run: |
          vendor/bin/phpunit --filter HalfOptimizedFixturesTest

    - name: Run PHPUnit Fully optimized fixtures
      env:
        DATABASE_TEST_URL: 'sqlserver://@(localdb)\MSSQLLocalDB/cbench'
      run: |
          vendor/bin/phpunit --filter FullyOptimizedFixturesTest
